### ISSUE TITLE
执行命令长时间没反应 (Reply: 安卓端下载的qsv可能解析有些问题，PC端下载的则是可以成功转换的)

### ISSUE THREAD

**Issue by jcconline** [zhangzhilinx/qsv2flv#1]
在爱奇艺下载了爱情公寓和请回答1988的1080p视频进行转换，发现执行命令后长时间没反应

**Comment by zhangzhilinx** [comment]
没有反应是因为程序默认不显示输出，需要输出的话可以加上-v参数（或者--verbose参数）

另外可以贴一下具体执行的命令吗？

**Comment by jcconline** [comment]
命令是：qsv2flv D:\\1.qsv D:\\1.flv
在长时间等待后终于出现了下面提示：
[ERROR] Couldn't convert 1.qsv to 1.flv: failed to fill whole buffer

**Comment by zhangzhilinx** [comment]
这是我这边运行的结果：

qsv2flv -v D:\Output\爱情公寓5第1集-蓝光1080P.qsv D:\Output\爱情公寓5第1集-蓝光1080P.flv
[STEP] Validate qsv file...
[STEP] Parse all tag blocks...
[STEP] Generate metadata from all tag blocks...
[STEP] Write from qsv to flv...
[INFO] Time cost: 14.105s

**Comment by jcconline** [comment]
我卡在了第二步
[STEP] Validate qsv file...
[STEP] Parse all tag blocks...

**Comment by zhangzhilinx** [comment]
解析需要一定时间，并不奇怪，看起来像是卡住了

可以先试着用爱奇艺自带的播放器测试一下看看是否是qsv文件发生了损坏
我在这边写完之后测试了不少qsv，并没有发生这类问题，基本都能转换
如果qsv文件是正常的话，有可能是爱奇艺又改了它们的视频格式吧

**Comment by zhangzhilinx** [comment]
哥们，现在情况怎么样啊？

failed to fill whole buffer是read_exact()报的错，读取的时候没有成功读取完所有期望的字节数，比如说有时候可能是qsv没下载完全或者下载过程中出错，可能就会发生这样的问题

**Comment by zhangzhilinx** [comment]
@jcconline 哥们，现在情况怎么样啊？

failed to fill whole buffer是read_exact()报的错，读取的时候没有成功读取完所有期望的字节数，比如说有时候可能是qsv没下载完全或者下载过程中出错，可能就会发生这样的问题

**Comment by jcconline** [comment]
用爱奇艺的播放器可用正常播放。下载过程中应该是没出错的，我是昨天用安卓最新版爱奇艺APP下载的视频。测试了爱情公寓5和请回答1988的1080p视频。但这两个视频都是需要会员才能看和下载，会不会是这个原因

**Comment by zhangzhilinx** [comment]
@jcconline 不会，我也测试过一些会员视频，解析转换都是没有问题的。

不过我都是用PC端的爱奇艺下载的，我之前下的爱5全系列都能转换，转换之后可以用其它播放器观看，有可能是APP版本的爱奇艺下载下来的格式不太对，不妨试下用PC版下载的QSV，不过我现在没会员了，没办法测试你说的《请回答1988》

第一步能通过，说明QSV的文件头是没有问题的，所以我也很疑惑

**Comment by jcconline** [comment]
测试了PC端下载的视频可以转换

**Comment by zhangzhilinx** [comment]
@jcconline 可以就好，那我关闭这个issue啦
如果可以的话，也帮忙解析下手机端的qsv视频格式，我把issue名字改改
