### ISSUE TITLE
您好，我在转换视频的时候出现以下错误，请问怎么回事呀

### ISSUE THREAD

**Issue by huangfeibang** [zhangzhilinx/qsv2flv#2]
Couldn't convert .\668374600_668374600.qsv to test2.flv: failed to fill whole buffer

**Comment by zhangzhilinx** [comment]
不好意思，最近没怎么关注github
* 是PC端下载的qsv吗？
* 是否确认下载完整？有没有下载受损？
* 有没有尝试过用稍旧的爱奇艺版本下载测试？

**Comment by LTsKi** [comment]
使用爱奇艺7.6.114.1948 下载的720P QSV转换也遇到的同样的问题，影视文件是完整的
错误：
[ERROR] Couldn't convert C:/视频/test.qsv to C:/视频/test1.flv: failed to fill whole buffer

**Comment by huangfeibang** [comment]
好的，谢谢!



---原始邮件---
发件人: "ljj17173"<notifications@github.com&gt;
发送时间: 2020年7月31日(周五) 下午4:01
收件人: "zhangzhilinx/qsv2flv"<qsv2flv@noreply.github.com&gt;;
抄送: "huangfeibang"<1058677384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhangzhilinx/qsv2flv] 您好，我在转换视频的时候出现以下错误，请问怎么回事呀 (#2)




 
使用爱奇艺7.6.114.1948 下载的720P QSV转换也遇到的同样的问题，影视文件是完整的
 错误：
 [ERROR] Couldn't convert C:/视频/test.qsv to C:/视频/test1.flv: failed to fill whole buffer

**Comment by zhangzhilinx** [comment]
> 
> 
> 使用爱奇艺7.6.114.1948 下载的720P QSV转换也遇到的同样的问题，影视文件是完整的
> 错误：
> [ERROR] Couldn't convert C:/视频/test.qsv to C:/视频/test1.flv: failed to fill whole buffer

failed to fill whole buffer的直接原因是程序没有读取够期望的字节数
似乎是该qsv可能已经不符合程序的设计
可以暂时修改代码，加入dbg!重新编译运行，这样程序可以报告发生错误的代码行数，帮助定位问题发生的位置
另外能否分享一下相关qsv视频呢？

**Comment by zhangzhilinx** [comment]
这个issue已经很长时间没有后续提交，就先暂时关闭啦
