### ISSUE TITLE
您好，请问qsv格式文件的结构信息可以从哪里查到

### ISSUE THREAD

**Issue by supernova4869** [zhangzhilinx/qsv2flv#4]
您好，请问如何得知qsv格式文件的详细结构信息呢？我目前只知道文件前10个字符是“QIYI VIDEO”。

**Comment by zhangzhilinx** [comment]
这么晚了还不睡呢？😁
可以在convert_qsv.rs中详读代码来分析哦

**Comment by zhangzhilinx** [comment]
结合README中简单提到的函数组织结构来进一步分析，三言两语不容易说清楚，网上似乎没有人专门写博客说明qsv的文件结构

**Comment by supernova4869** [comment]
谢谢这么快回答！😁好的，我开完组会之后专门研究一下，非常感谢~

**Comment by martinidea** [comment]
大佬您好，现在mac m1发现好像不支持耶，不知道是什么原因提示：failed to fill whole buffer
如果可以希望编绎出m1 mac版本的。也可能是我爱奇艺版本的问题，我的版本是11.12.5，下载后的程序藏得很深。而且文件名非原来视频名，并附带一个qsv.star文件。文件内容如下：
[{"sl":"214316805","vl":[{"ep":619,"sp":473},{"ep":913,"sp":705},{"ep":1661,"sp":959},{"ep":1876,"sp":1862},{"ep":2139,"sp":2073},{"ep":2285,"sp":2205},{"ep":2582,"sp":2351}]},{"sl":"200028905","vl":[{"ep":693,"sp":680},{"ep":959,"sp":928},{"ep":1955,"sp":1881}]}]

**Comment by zyfdegh** [comment]
QSV文件格式简单分析
https://blog.csdn.net/qq446252221/article/details/7362348
这篇博文比较旧了可能，另外这个 repo 也有说明格式
https://github.com/btnkij/qsv2flv

**Comment by zhangzhilinx** [comment]
> QSV文件格式简单分析
> https://blog.csdn.net/qq446252221/article/details/7362348
> 这篇博文比较旧了可能，另外这个 repo 也有说明格式
> https://github.com/btnkij/qsv2flv



> 谢谢这么快回答！😁好的，我开完组会之后专门研究一下，非常感谢~

这个repo确实文档详细些，可以参考下

**Comment by zhangzhilinx** [comment]
那我就关掉这个issue啦 @supernovaZhangJiaXing
