### ISSUE TITLE
转换飞虎队视频报错

### ISSUE THREAD

**Issue by StrollStars** [zhangzhilinx/qsv2flv#8]
目标视频：飞虎队第一集
链接：https://www.iqiyi.com/v_19rroa7j4g.html
方式：通过爱奇艺客户端下载
结果：
Z:\>x86_64-pc-windows-msvc-qsv2flv.exe 飞虎队第1集-超清720P.qsv 1.flv
[ERROR] Couldn't convert 飞虎队第1集-超清720P.qsv to 1.flv: failed to fill whole buffer

**Comment by zhangzhilinx** [comment]
请使用旧版本的爱奇艺下载并转换，新版本似乎改变了加密格式 @StrollStars

**Comment by StrollStars** [comment]
@zhangzhilinx 请问用哪个版本的合适？

**Comment by zhangzhilinx** [comment]
> @zhangzhilinx 请问用哪个版本的合适？

尽量用2019年发布的版本

**Comment by StrollStars** [comment]
没找到2019年的版本，下载了2018年的6.6版本，发现下载存在问题。

**Comment by StrollStars** [comment]
@zhangzhilinx 6.6版已无法下载，6.8版可行，谢谢。
